### ISSUE TITLE
can I use SeqLib at my C scripts?

### ISSUE THREAD

**Issue by zeronot** [walaj/SeqLib#14]
HI,
    I  need to write C scripts to deal with bam , and I wanna use SeqLib  ,other than htslib, but I am not sure 
whether SeqLib is work .
   I do not want to use htslib,because it can provide enough examples to tell me how to use .I think your library is better .

**Comment by walaj** [comment]
@zeronot 

Thanks for your interest, although I should say that htslib is an incredible library -- this is just a C++ face on top of it. If you can use C++ (but not C) for your project, this should work for nearly all BAM processing needs. Let me know if any issues if you end up trying this.

Best,
Jeremiah

**Comment by zeronot** [comment]
Thanks! I will have a try . keep contact . @walaj
