### ISSUE TITLE
how to know mismatch base position and cigar value of every base at a read ?

### ISSUE THREAD

**Issue by zeronot** [walaj/SeqLib#15]
HI,Author,
   I wanna use SeqLib to deal with BAM  files  to know mismatch base position and cigar value of every base at a read .  for example, we get a read from BAM records , cigar string is 2S3M2I2M ,the read sequence is 
'ATCGGCATG'. So I wanna get mismatch index at this read and get cigar value for every base at this read  ,the final result ,just like this : ('m' meand mismatch ) 
A T C  G  G  C  A  T   G
S S M m M  I    I   M   M 

thank you！

**Comment by walaj** [comment]
It'll be tough for me to guide you much on this given my time constraints, but I would refer you to the API documentation here: https://walaj.github.io/seqlibdocs/doxygen/ Issues are more for true issues / bugs with the code. 

At any rate, the things to look at are BamReader, BamRecord and Cigar. You can pull a Cigar out of a BamRecord (an individual read) and loop through the CigarField objects to get what you need.

Also check out https://github.com/walaj/bxtools/blob/master/src/bxmol.cpp for an example of using a BamReader to get BamRecord objects.
