### ISSUE TITLE
can't Compile successful

### ISSUE THREAD

**Issue by MyandMine** [walaj/SeqLib#17]
![image](https://cloud.githubusercontent.com/assets/12637272/23501304/5adee3d2-ff6e-11e6-8e11-f6dd478f1536.png)

why？
do I forget something?

**Comment by walaj** [comment]
Can you give us a bit more than that? How did you clone, configure and run make?

**Comment by MyandMine** [comment]
![image](https://cloud.githubusercontent.com/assets/12637272/23533380/6df72bae-ffec-11e6-9cf6-b044a735e155.png)
I follow the guide，but when I use the order "make".
the errors were happen.
At first, I use the order `git clone --recursive https://github.com/walaj/SeqLib.git` to clone the soft in my windows compute, then I copy it to a linux server. 
Due to I am not have enough authority, I can't install it in the default directory.
So I use the order: `./configure --prefix="absolute path"`, then `make`.

**Comment by MyandMine** [comment]
OK, I have solved the problem.
I download the every file.
git clone https://github.com/walaj/SeqLib.git
git clone git@github.com:samtools/htslib.git
...
...
then every thing is ok.

**Comment by walaj** [comment]
I'm not sure. I still don't have enough information in your issue report to recreate this. The installation works as the documentation describes on all the systems I tested on.
