### ISSUE TITLE
Could SeqLib and htslib work out what a public cram api should be?

### ISSUE THREAD

**Issue by detrout** [walaj/SeqLib#21]
Hello,

In investigating packaging issues with htslib on Debian, we discovered that SeqLib is using functions htslib considers private (anything in cram/*.h)

Debian modified htslib to allow linking to the cram functions in the normal shared library, but the htslib developers have told us to not do that. Normally you're using an embedded copy of htslib, and can directly access private functions.

In an ideal world htslib would actually have a supported public cram API.

Could you talk a bit with the htslib developers about what you'd actually need from them?

**Comment by tillea** [comment]
It would be really cool if you could develop some solution for this.

**Comment by detrout** [comment]
I asked my coworker who's going to a conference that the cram & htslib developers will also be at next week to ask them about having library API for working with cram files.
