### ISSUE TITLE
Example showing how to compile my own program containing SeqLib

### ISSUE THREAD

**Issue by alifare** [walaj/SeqLib#22]
I am using SeqLib in my own program, because I need to align DNA sequences with BWA-MEM in memory.

Now I am struggling with an endless stream of compiling errors, so can you give me a complete example showing how to compile my program containing SeqLib?

**Comment by walaj** [comment]
Is the problem with compiling SeqLib or with the program you are linking with?

**Comment by alifare** [comment]
There's no problem in compiling both SeqLib and my own program respectively. But when I #include "SeqLib/RefGenome.h" and "SeqLib/BWAWrapper.h" , and compile and link the new program, a lot of problems appeared.
