### ISSUE TITLE
ChrName function in BamRecord Class logic wrong

### ISSUE THREAD

**Issue by vanNul** [walaj/SeqLib#35]
hello, I have found a little logic mistake in a function listed below, would you please fix it?
branch: master
file: https://github.com/walaj/SeqLib/blob/master/SeqLib/BamRecord.h
function: inline std::string ChrName(const SeqLib::BamHeader& h) const 
line: 829
code:   if (h.isEmpty()) should be  if (!h.isEmpty())

**Comment by walaj** [comment]
Thanks for finding this! Fixed.
