### ISSUE TITLE
Some functionality enchancement

### ISSUE THREAD

**Issue by vanNul** [walaj/SeqLib#41]
Hello walaj:
I have been using your excellent library SeqLib for sometime, in this period, I have added some functionality which will do some good to my own work. You're welcome to put these functionality into your original repository if it's worth and I will be much happier. I myself have tested these functionality and they work properly as I wished in my work.
All the functionality I have made is recorded in the following file:
https://github.com/vanNul/SeqLib/blob/master/change.md

**Comment by walaj** [comment]
Awesome! Would you be able to do a pull request with these changes? It'll be easier to review the differences.

**Comment by walaj** [comment]
BTW when you do the PR, can you separate out the bwa/hts updates from the SeqLib changes you made? It would be good to review these incrementally.

**Comment by vanNul** [comment]
Okay, I have figured out how to make a pull request, and make it in
https://github.com/walaj/SeqLib/pull/42
