### ISSUE TITLE
Libraries are placed in {prefix}/bin and not {prefix}/lib

### ISSUE THREAD

**Issue by edawson** [walaj/SeqLib#45]
When building from source, my libseqlib.a, libbwa.a, libhts.a and libfml.a all get placed in a directory called `bin`. I'd usually expect this directory to contain binaries, and to find libraries in a directory called `lib`. This isn't a huge deal, but it does kind of throw off my automated install processes. PR https://github.com/walaj/SeqLib/pull/44 tweaks the Makefile.am to change this.

**Comment by walaj** [comment]
Closing per the accepted PR. 
(Unrelatedly, am keen to check out the assembly graph work / svaha etc. Looks great, will give it a spin).
