### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by lqsae** [walaj/SeqLib#62]

**Comment by lqsae** [comment]
hi!
my main cpp code is:
#include <iostream>
#include "SeqLib/BWAWrapper.h"
#include "SeqLib/GenomicRegion.h"
using namespace SeqLib;
using namespace std;
int main()
{
    RefGenome ref;
    ref.LoadIndex("hg19.fasta");
    std::string seq = ref.QueryRegion("1", 1000000,1001000);
    cout <<seq<<endl;
    return 0;

}

when i run :  g++ main.cpp -std=c++11 -I/home/lqs/biosoft/SeqLib/  -L/home/lqs/biosoft/SeqLib/lib -lhts -lbwa -lfml -lseqlib
main.cpp:36:5: error: ‘RefGenome’ was not declared in this scope
can you help me?

**Comment by walaj** [comment]
Missing `#include SeqLib/RefGenome.h`
