### ISSUE TITLE
Improvement: Remove use of "__" reserved C++ prefix

### ISSUE THREAD

**Issue by rob-p** [walaj/SeqLib#9]
Hi all,

  I'm *very* excited to see this project!  I've had the experience of replacing BamTools with htslib + samtools in the past before to reap the substantial speed improvements it provides.  Of course, the interface is not nearly as nice, and I miss the nice, clean, c++ interface provided by BamTools.  SeqLib seems like a great solution to this tradeoff.

  Anyway, on to my issue.  The use of `__` as a prefix is [reserved in C and C++ for implementation and library-specific use](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier).  Therefore, it's highly desirable to avoid beginning variables, functions or methods with `__` as a prefix.  Though I'm sure there is likely no conflict at this point, it's best to observe this rule to avoid potential naming conflicts in the future (and because all such names are technically reserved for the language).

--Rob

**Comment by walaj** [comment]
Hi Rob,

Very good to hear you're finding this project useful! Will be nice to have more users to continue to exercise and improve the code.

You make a good point about the naming convention, I've had others suggest I move away from it. Thanks for the link. It seems they suggest to avoid __ in general. I made some other changes, and removed most of the __ while I was at it.
